language: python
python:
  - "pypy"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install --upgrade setuptools tox tox-travis coveralls flit
  - flit install --deps all  # TODO adapt what needs to be in python 2.7
script:
  - tox
  - flit build
after_success:
  - coveralls
