[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "connexion"
author = "Zalando SE"
author-email = "opensource@zalando.de"
description-file = "README.rst"
home-page = "https://github.com/zalando/connexion/"
requires = [
    "clickclick>=1.2",
    "jsonschema>=2.5.1,<3.0.0",
    "PyYAML>=3.11",
    "requests>=2.9.1",
    "six>=1.9",
    "inflection>=0.3.1",
    "pathlib>=1.0.1; python_version < '3.4'",
    "typing>=3.6.1; python_version < '3.6'",
    "openapi-spec-validator>=0.2.4",
    "flask>=0.10.1"
]
classifiers=[
    "Programming Language :: Python",
    "Programming Language :: Python :: 2.7",
    "Programming Language :: Python :: 3.4",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
    "Topic :: Software Development :: Libraries :: Application Frameworks"
]

[tool.flit.metadata.requires-extra]
aiohttp = [
    "aiohttp>=2.3.10",
    "aiohttp-jinja2>=0.14.0"
]
flask = ["flask>=0.10.1"]
swagger-ui = ["swagger-ui-bundle>=0.0.2"]
test = [
    "decorator",
    "mock",
    "pytest",
    "pytest-cov",
    "testfixtures",
    "flask>=0.10.1",
    "swagger-ui-bundle>=0.0.2"
]
ujson = ["ujson>=1.35"]


[tool.flit.scripts]
connexion = "connexion.cli:main"
